### ISSUE TITLE
Container log file size

### ISSUE THREAD

**Issue by samcro1967** [nylonee/watchlistarr#173]
After running this image for a few weeks, the container log file has grown to almost 200 GB.  I needed to reclaim space so I stopped the container, truncated the log file, limited the log file size, and restarted the container.  Not sure if this is normal/expected or if I have something misconfigured.

I added the following to docker compose if anyone else sees a similiar issue.
```
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```

Everything seems to be running normally
